config/routes.rb
Rails.application.routes.draw do
root 'products#index'
resources :products do
  collection { post :import }
end
post '/users/import' => 'users#import'
get '/transactions/destroy_all' => 'transactions#destroy_all'
resources :transactions do
  collection { post :import }
end
get '/holds/destroy_all' => 'holds#destroy_all'
post '/holds/import' => 'holds#import'
resources :holds do
  collection { post :import }
end
post '/transactions/import' => 'transactions#import'
get '/transactions' => 'transactions#index'
# get '/users/process/:id' => 'users#process_user'
get '/users/unprocess/:id' => 'users#unprocess_user'
post '/users/search'
post '/users/process' => 'users#process_user'
get '/users_download' => 'users#users_download'
get '/users/:id' => 'users#view'
get '/holds' => 'holds#index'
get '/international' => 'transactions#international'
get '/key/up' => 'transactions#key_up'
get '/key/down' => 'transactions#key_down'
get '/invoice/up' => 'transactions#invoice_up'
get '/invoice/down' => 'transactions#invoice_down'
get '/agent_id/up' => 'transactions#agent_id_up'
get '/agent_id/down' => 'transactions#agent_id_down'
get '/c2go_id/up' => 'transactions#c2go_id_up'
get '/c2go_id/down' => 'transactions#c2go_id_down'
get '/issue_date/up' => 'transactions#issue_date_up'
get '/issue_date/down' => 'transactions#issue_date_down'
get '/itinerary/up' => 'transactions#itinerary_up'
get '/itinerary/down' => 'transactions#itinerary_down'
get '/active/up' => 'transactions#active_up'
get '/active/down' => 'transactions#active_down'
get '/commission_total/up' => 'transactions#commission_total_up'
get '/commission_total/down' => 'transactions#commission_total_down'
get '/agent_total/up' => 'transactions#agent_total_up'
get '/agent_total/down' => 'transactions#agent_total_down'
get '/upline_total/up' => 'transactions#upline_total_up'
get '/upline_total/down' => 'transactions#upline_total_down'
get '/evo_total/up' => 'transactions#evo_total_up'
get '/evo_total/down' => 'transactions#evo_total_down'
get '/processed/up' => 'transactions#processed_up'
get '/processed/down' => 'transactions#processed_down'
get '/make_upline_transactions' => 'transactions#create_upline_transactions'
get '/update_active_status' => 'transactions#update_active_status'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
  collection { post :import }
end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :transactions
	def self.import(file, inactive)
	  spreadsheet = Roo::Spreadsheet.open(file.path)
	  header = spreadsheet.row(1)
		(2..spreadsheet.last_row).each do |i|
			row = Hash[[header, spreadsheet.row(i)].transpose]
			user = find_by(evo_id: row["ID"]) || new
			user.evo_id = row['ID']
			user.upline_id = row['SponsorID']
			user.first = row['FirstName']
			user.last = row['LastName']
			user.c2go = row['C2GONumber']
			user.web_name = row['WebRepName']
			user.address = row['Address']
			user.apt = row['Apt']
			user.city = row['City']
			user.state = row['State']
			user.zip = row['Zip']
			user.country = row['Country']
			user.phone = row['Cellular']
			user.email = row['Email']
			if user.processed == true
			else
				user.processed = false
			end
			if inactive
				user.active = false
			else
				user.active = true
			end
			user.save!
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def import
		if params['inactive']
			User.import(params[:file], true)
		else
			User.import(params[:file], false)
		end
		redirect_to '/'
		flash[:imported] = "Users Imported"
	end
	def view
		@user = User.find(params[:id])
		@upline_user = User.find_by(evo_id: @user.upline_id) if @user
		@pending = Transaction.where(agent_id: @user.evo_id) if @user
		@upline = Transaction.where(upline_id: @user.evo_id) if @user
		@holds_pending = Hold.where(evo_id: @user.evo_id) if @user
		@upline_holds_pending = Hold.where(evo_id: @upline_user.evo_id) if @upline_user
	end
	def international
		session[:page] = 'int'
		@users = User.where("country != ? or country is null", "US")
	end
	def process_user
		@user = User.find(params['user_id'])
		@ret_ids_array = JSON.parse(params['retain_ids'])
		@to_destroy = []
		@holds = Hold.where(evo_id: @user.evo_id)
		@holds.each do |val|
			found = false
			@ret_ids_array.each do |inner_val|
				if val.id == inner_val.to_i
					found = true
				else
				end
			end
			if found
			else
				@to_destroy << val
			end
		end
		@to_destroy.each do |val|
			val.destroy
		end
		Transaction.where(agent_id: @user.evo_id).destroy_all
		@user.update_attribute(:processed, true)
		redirect_to "/users/#{@user.id}"
	end
	def unprocess_user
		@user = User.find(params['id'])
		@user.update_attribute(:processed, false)
		redirect_to "/users/#{@user.id}"
	end
	def search
		@user = User.find_by(evo_id: params['id'])
		if @user
			redirect_to "/users/#{@user.id}" and return
		else
			flash[:imported] = "No user found"
			redirect_to "/transactions" and return
		end
	end
	def users_download
		@users = User.all
		@retained = BigDecimal.new("0")
		@users.each do |val|
			if !val.active
				@upline_commissions = Transaction.where(upline_id: val.evo_id)
				@upline_commissions.each do |com_val|
					@retained += BigDecimal.new(com_val.upline_total).round(2)
				end
			end
		end
	end
	def create
		respond_to do |format|
			format.html
			format.xls {
					@users = User.all.select("evo_id, revenue_type, c2go, first, last, agent_total, evo_total, active")
					@ret_arr = []
					@users.to_a.each do |val|
						@commissions = Transaction.where(agent_id: val.evo_id)
						@total = BigDecimal.new("0")
						@evo_total = BigDecimal.new("0")
						@upline_total = BigDecimal.new("0")
						@commissions.each do |com_val|
							@total += BigDecimal.new(com_val.agent_total).round(2) if com_val.agent_total
							@evo_total += BigDecimal.new(com_val.evo_total).round(2) if com_val.evo_total
							val.revenue_type = com_val.revenue_type if com_val.revenue_type
						end
						if val.active
							@upline_commissions = Transaction.where(upline_id: val.evo_id)
							@upline_commissions.each do |com_val|
								@total += BigDecimal.new(com_val.upline_total).round(2) if com_val.upline_total
							end
						end
						@holds_pending = Hold.where(evo_id: val.evo_id)
						@holds_pending.each do |com_val|
							@total += BigDecimal.new(com_val.paid_agent) if com_val.paid_agent
						end
						val.agent_total = @total
						val.evo_total = @evo_total
					end
					@users.order(agent_total: :desc)
				# session[:page] = 'all'
				send_data(@users.to_a.to_xls) 
			}
		end 
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/international.html.erb
<style type="text/css">
	.btn-row button{
		display: inline-block;
		margin-left: 20px;
	}
	.btn-row form{
		display: inline-block;
		margin-left: 20px;
	}
</style>
<div class="container-fluid">
	<div class="row btn-row">
	<%= button_to 'Excel Download', transactions_path(:format => :xls), class: 'btn btn-primary' %>
	<a href="/transactions/destroy_all" data-confirm="Clear current chart?"><button class="btn btn-danger">Clear Currenct</button></a>
	</div>
<table class="table table-responsive table-striped">
	<thead>
		<tr>
		<th>Agent ID</th>
		<th>C2GO ID</th>
		<th>Agent Name</th>
		<th>Country</th>
		<th>Upline ID</th>
		<th>Upline Name</th>
		<th>Processed</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |val| %>
			<tr>
				<td><%= val.evo_id %></td>
				<td><%= val.c2go %></td>
				<td><a href="/users/<%= val.id %>"><%= val.first %> <%= val.last %></a></td>
				<td><%= val.country %></td>
				<td><%= val.upline_id %></td>
				<% @upline = User.find_by(evo_id: val.upline_id) %>
				<% if @upline %>
				<td><%= @upline.first %> <%= @upline.last %></td>
				<% else %>
				<td></td>
				<% end %>
				<% if @user.processed %>
					<td class="green">Processed</td>
				<% else %>
					<td class="red">Not Processed</td>
				<% end %>
				</tr>
			</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/users/users_download.html.erb
<style type="text/css">
	.container{
		margin-top: 100px;
	}
</style>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
		<%= button_to 'User Download', users_path(:format => :xls), class: 'btn btn-primary' %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<h3>Retained from Inactive Uplines: <%= number_to_currency(@retained) %></h3>
		</div>
	</div>
</div>

app/views/users/view.html.erb
<style type="text/css">
	.green{
		color: green;
	}
	.red{
		color: red;
	}
	.header-col h3{
		display: inline-block;
		margin-left: 50px;
	}
	.header-col h2{
		display: inline-block;
	}
	.payout{
		margin-bottom: 20px;
	}
</style>
<% @total = BigDecimal.new("0") %>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 header-col">
			<h2><%= @user.first %> <%= @user.last %></h2>
			<h3>Evo ID: <%= @user.evo_id %></h3>
			<h3>Upline: <a href="/users/<%= @upline_user.id %>"><%= @upline_user.first %> <%= @upline_user.last %></a></h3>
 			<% if @user.c2go %>
				<h3>C2GO ID: <%= @user.c2go %></h3>
			<% end %>
		</div>
	</div>
	<% if !@user.active %>
		<div class="row">
			<div class="col-sm-12">
				<h3 class="red">INACTIVE</h3>
			</div>
		</div>
	<% end %>
	<h3>Pending Commission Payouts:</h3>
	<table class="table table-responsive table-striped">
		<thead>
			<tr>
			<th>Invoice</th>
			<th>Traveler</th>
			<th>Itinerary</th>
			<th>Commission Total</th>
			<th>Evolution Commission</th>
			<th>Upline Commission</th>
			<th>Agent Commission</th>
			</tr>
		</thead>
		<tbody>
			<% @pending.each do |val| %>
				<% if val.commission_total != 0 %>
					<tr>
					<td><%= val.invoice %></td>
					<td><%= val.traveler %></td>
					<td><%= val.itinerary %></td>
					<td><%= number_to_currency(val.commission_total) %></td>
					<td><%= number_to_currency(val.evo_total) %></td>
					<td><%= number_to_currency(val.upline_total) %></td>
					<td class="green"><%= number_to_currency(val.agent_total) %></td>
					<% @total += BigDecimal.new(val.agent_total).round(2) %>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
	<h3>Pending Upline Payouts:</h3>
	<% if @upline.length > 0 %>
	<table class="table table-responsive table-striped">
		<thead>
			<tr>
			<th>Invoice</th>
			<th>Traveler</th>
			<th>Itinerary</th>
			<th>Commission Total</th>
			<th>Evolution Commission</th>
			<th>Agent Commission</th>
			<th>Upline Commission</th>
			</tr>
		</thead>
		<tbody>
			<% @upline.each do |val| %>
				<% if val.commission_total != 0 %>
					<tr>
					<td><%= val.invoice %></td>
					<td><%= val.traveler %></td>
					<td><%= val.itinerary %></td>
					<td><%= number_to_currency(val.commission_total) %></td>
					<td><%= number_to_currency(val.evo_total) %></td>
					<td><%= number_to_currency(val.agent_total) %></td>
					<% if val.upline_total > 0 %>
						<td class="green"><%= number_to_currency(val.upline_total) %></td>
					<% else %>
						<td class="red"><%= number_to_currency(val.upline_total) %></td>
					<% end %>
					<% if @user.active %>
						<% @total += BigDecimal.new(val.upline_total).round(2) %>
					<% end %>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
	<% else %>
	<h5>No Upline Payouts Found</h5>
	<% end %>
	<h3>Pending Recalls/Holds:</h3>
	<% if @holds_pending.length > 0 %>
	<table class="table table-responsive table-striped">
		<thead>
			<tr>
			<th>Retain</th>
			<th>Invoice</th>
			<th>Traveler</th>
			<th>Itinerary</th>
			<th>Method</th>
			<th>Evolution Commission</th>
			<th>Upline Commission</th>
			<th>Paid Agent</th>
			</tr>
		</thead>
		<tbody>
			<% @holds_pending.each do |val| %>
					<tr>
					<td><input type="checkbox" class="retain_check" value="<%= val.id %>"></td>
					<td><%= val.invoice %></td>
					<td><%= val.traveler %></td>
					<td><%= val.itinerary %></td>
					<td><%= val.method %></td>
					<td><%= number_to_currency(val.upline) %></td>
					<td><%= number_to_currency(val.upline) %></td>
					<% if val.paid_agent > 0 %>
					<td class="red">+<%= number_to_currency(val.paid_agent) %></td>
					<% else %>
					<td class="red"><%= number_to_currency(val.paid_agent) %></td>
					<% end %>
						<% @total += BigDecimal.new(val.paid_agent).round(2) %>
					</tr>
			<% end %>
		</tbody>
	</table>
	<% else %>
	<h5>No Recalls/Holds Found</h5>
	<% end %>
	<div class="payout">
		<% if @total > 0 %>
		<h3>Payout Ammount: <span class="green"><%= number_to_currency(@total.round(2)) %></span></h3>
		<% else %>
		<h3>Payout Ammount: <span class="red"><%= number_to_currency(@total.round(2)) %></span></h3>
		<% end %>
		<% if !@user.processed %>
			<form action="/users/process" accept-charset="UTF-8" method="post" class="form-vertical">
			<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
			<input name="retain_ids" type="hidden" id="retain_ids">
			<input name="user_id" type="hidden" value="<%= @user.id %>">
				<button class="btn btn-primary" data-confirm="Process?">Process</button>
			</form>
		<% else %>
			<h3 class="green">Processed</h3>
			<a href="/users/unprocess/<%= @user.id %>" data-confirm="Mark as unprocessed?"><button class="btn btn-danger">Re-Open</button></a>
		<% end %>
	</div>
</div>

<script type="text/javascript">
	$( document ).on('turbolinks:load', function() {
		var retain_ids_arr = [];
		$('.retain_check').click(function(){
			if($(this).is(':checked')){
				console.log($(this).val());
				retain_ids_arr.push($(this).val());
				$('#retain_ids').val(JSON.stringify(retain_ids_arr));
			}
			else{
				var i = retain_ids_arr.indexOf($(this).val());
				retain_ids_arr.splice(i, 1);
				$('#retain_ids').val(JSON.stringify(retain_ids_arr));
				console.log("remove value");
			}
		})
	})
</script>