config/routes.rb
Rails.application.routes.draw do
root 'products#index'
resources :products do
  collection { post :import }
end
post '/users/import' => 'users#import'
get '/transactions/destroy_all' => 'transactions#destroy_all'
resources :transactions do
  collection { post :import }
end
get '/holds/destroy_all' => 'holds#destroy_all'
post '/holds/import' => 'holds#import'
resources :holds do
  collection { post :import }
end
post '/transactions/import' => 'transactions#import'
get '/transactions' => 'transactions#index'
# get '/users/process/:id' => 'users#process_user'
get '/users/unprocess/:id' => 'users#unprocess_user'
post '/users/search'
post '/users/process' => 'users#process_user'
get '/users_download' => 'users#users_download'
get '/users/:id' => 'users#view'
get '/holds' => 'holds#index'
get '/international' => 'transactions#international'
get '/key/up' => 'transactions#key_up'
get '/key/down' => 'transactions#key_down'
get '/invoice/up' => 'transactions#invoice_up'
get '/invoice/down' => 'transactions#invoice_down'
get '/agent_id/up' => 'transactions#agent_id_up'
get '/agent_id/down' => 'transactions#agent_id_down'
get '/c2go_id/up' => 'transactions#c2go_id_up'
get '/c2go_id/down' => 'transactions#c2go_id_down'
get '/issue_date/up' => 'transactions#issue_date_up'
get '/issue_date/down' => 'transactions#issue_date_down'
get '/itinerary/up' => 'transactions#itinerary_up'
get '/itinerary/down' => 'transactions#itinerary_down'
get '/active/up' => 'transactions#active_up'
get '/active/down' => 'transactions#active_down'
get '/commission_total/up' => 'transactions#commission_total_up'
get '/commission_total/down' => 'transactions#commission_total_down'
get '/agent_total/up' => 'transactions#agent_total_up'
get '/agent_total/down' => 'transactions#agent_total_down'
get '/upline_total/up' => 'transactions#upline_total_up'
get '/upline_total/down' => 'transactions#upline_total_down'
get '/evo_total/up' => 'transactions#evo_total_up'
get '/evo_total/down' => 'transactions#evo_total_down'
get '/processed/up' => 'transactions#processed_up'
get '/processed/down' => 'transactions#processed_down'
get '/make_upline_transactions' => 'transactions#create_upline_transactions'
get '/update_active_status' => 'transactions#update_active_status'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
  collection { post :import }
end
end

app/models/hold.rb
class Hold < ApplicationRecord
  	def self.import(file)
	  spreadsheet = Roo::Spreadsheet.open(file.path)
	  header = spreadsheet.row(1)
		(2..spreadsheet.last_row).each do |i|
			row = Hash[[header, spreadsheet.row(i)].transpose]
			hold = find_by(key: row["key"]) || new
			user = User.find_by(evo_id: row['evo_id'])
			if user
				hold.key = row['key']
				hold.evo_id = row['evo_id']
				hold.acct = row['acct']
				hold.invoice = row['invoice']
				hold.issue_date = row['issue_date']
				hold.rev = row['rev']
				hold.traveler = row['traveler']
				hold.dep_date = row['dep_date']
				hold.ret_date = row['ret_date']
				hold.fare_total = row['fare_total']
				hold.comm_total = row['comm_total']
				hold.air = row['air']
				hold.eight_nine = row['eight_nine']
				hold.upline = row['upline']
				hold.paid_agent = row['paid_agent']
				hold.method = row['method']
				hold.ticket = row['ticket']
				hold.itinerary = row['itinerary']
				hold.name = row['name']
				hold.c2go = row['c2go']
				hold.email = row['email']
				hold.save!
			end
		end
	end
end

app/controllers/holds_controller.rb
class HoldsController < ApplicationController
	def import
	  Hold.import(params[:file])
	  flash[:imported] = "Holds imported"
	  redirect_to '/'
	end
	def index
		@holds = Hold.all
	end
	def destroy_all
		Hold.destroy_all
		flash[:imported] = "Holds cleared"
		redirect_to '/'
	end
	def create
		@holds = Hold.all
		  respond_to do |format|
		  	@holds.to_a.each do |val|
		  		@u = User.find_by(evo_id: val.evo_id)
		  		if @u.first && @u.last
			  		val.name = @u.first + " " + @u.last
			  	end
			  	if @u.email
			  		val.email = @u.email
			  	end
			  	if @u.c2go
					val.c2go = @u.c2go
				end
			end
		    # format.html # don't forget if you pass html
		    format.xls { send_data(@holds.to_a.to_xls) }
		    # format.xls {
		    #   filename = "Posts-#{Time.now.strftime("%Y%m%d%H%M%S")}.xls"
		    #   send_data(@posts.to_xls, :type => "text/xls; charset=utf-8; header=present", :filename => filename)
		    # }
		  end
	end
end

app/helpers/holds_helper.rb
module HoldsHelper
end

app/views/holds/index.html.erb
<style type="text/css">
	.red{
		color: red;
	}
	.btn-row button{
		display: inline-block;
		margin-left: 20px;
	}
	.btn-row form{
		display: inline-block;
		margin-left: 20px;
	}
</style>
<div class="container-fluid">
	<div class="row btn-row">
	<%= button_to 'Excel Download', holds_path(:format => :xls), class: 'btn btn-primary' %>
	<a href="/holds/destroy_all" data-confirm="Clear current chart?"><button class="btn btn-danger">Clear Currenct</button></a>
	</div>
	<table class="table table-responsive table-striped">
		<thead>
			<tr>
			<th>Key</th>
			<th>Evolution ID</th>
			<th>C2GO ID</th>
			<th>Invoice</th>
			<th>Account</th>
			<th>Name</th>
			<th>Itinerary</th>
			<th>Issue_Date</th>
			<th>Method</th>
			<th>Paid Agent</th>
			<th>Processed</th>
			</tr>
		</thead>
		<tbody>
			<% @holds.each do |val| %>
					<tr>
					<td><%= val.key %></td>
					<td><%= val.evo_id %></td>
					<td><%= val.c2go %></td>
					<td><%= val.invoice %></td>
					<td><%= val.acct %></td>
					<% @user = User.find_by(evo_id: val.evo_id) %>
					<td><a href="/users/<%= @user.id %>"><%= @user.first %> <%= @user.last %></a></td>
					<td><%= val.itinerary %></td>
					<% if val.issue_date %>
					<td><%= val.issue_date.strftime("%m/%d/%y") %></td>
					<% else %>
					<td></td>
					<% end %>
					<td><%= val.method %></td>
					<td class="red"><%= number_to_currency(val.paid_agent) %></td>
					<% if @user.processed %>
						<td class="green">Processed</td>
					<% else %>
						<td class="red">Not Processed</td>
					<% end %>
					</tr>
			<% end %>
		</tbody>
	</table>
</div>